export const permissionSeedData = [
  { module: 'admin', resource: 'tenant', action: 'read', name: 'tenant:read' },
  { module: 'admin', resource: 'tenant', action: 'write', name: 'tenant:write' },
  { module: 'admin', resource: 'user', action: 'read', name: 'user:read' },
  { module: 'admin', resource: 'user', action: 'write', name: 'user:write' },
  { module: 'admin', resource: 'user', action: 'delete', name: 'user:delete' },
  { module: 'admin', resource: 'role', action: 'read', name: 'role:read' },
  { module: 'admin', resource: 'role', action: 'write', name: 'role:write' },
  { module: 'admin', resource: 'role', action: 'delete', name: 'role:delete' },
  { module: 'admin', resource: 'audit_log', action: 'read', name: 'audit_log:read' },
  { module: 'patient', resource: 'patient', action: 'read', name: 'patient:read' },
  { module: 'patient', resource: 'patient', action: 'write', name: 'patient:write' },
  { module: 'patient', resource: 'patient', action: 'delete', name: 'patient:delete' },
  { module: 'patient', resource: 'patient', action: 'export', name: 'patient:export' },
  {
    module: 'patient',
    resource: 'medical_record',
    action: 'read',
    name: 'medical_record:read',
  },
  {
    module: 'patient',
    resource: 'medical_record',
    action: 'write',
    name: 'medical_record:write',
  },
  {
    module: 'appointment',
    resource: 'appointment',
    action: 'read',
    name: 'appointment:read',
  },
  {
    module: 'appointment',
    resource: 'appointment',
    action: 'write',
    name: 'appointment:write',
  },
  {
    module: 'appointment',
    resource: 'appointment',
    action: 'delete',
    name: 'appointment:delete',
  },
  {
    module: 'appointment',
    resource: 'appointment',
    action: 'approve',
    name: 'appointment:approve',
  },
  {
    module: 'clinical',
    resource: 'prescription',
    action: 'read',
    name: 'prescription:read',
  },
  {
    module: 'clinical',
    resource: 'prescription',
    action: 'write',
    name: 'prescription:write',
  },
  {
    module: 'clinical',
    resource: 'prescription',
    action: 'approve',
    name: 'prescription:approve',
  },
  { module: 'clinical', resource: 'lab_order', action: 'read', name: 'lab_order:read' },
  { module: 'clinical', resource: 'lab_order', action: 'write', name: 'lab_order:write' },
  { module: 'clinical', resource: 'lab_result', action: 'read', name: 'lab_result:read' },
  { module: 'clinical', resource: 'lab_result', action: 'write', name: 'lab_result:write' },
  { module: 'pharmacy', resource: 'medication', action: 'read', name: 'medication:read' },
  { module: 'pharmacy', resource: 'medication', action: 'write', name: 'medication:write' },
  { module: 'pharmacy', resource: 'dispensing', action: 'write', name: 'dispensing:write' },
  { module: 'billing', resource: 'invoice', action: 'read', name: 'invoice:read' },
  { module: 'billing', resource: 'invoice', action: 'write', name: 'invoice:write' },
  { module: 'billing', resource: 'invoice', action: 'approve', name: 'invoice:approve' },
  { module: 'billing', resource: 'payment', action: 'read', name: 'payment:read' },
  { module: 'billing', resource: 'payment', action: 'write', name: 'payment:write' },
  { module: 'billing', resource: 'report', action: 'export', name: 'billing_report:export' },
] as const;
